version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test: 
    docker:
      - image: cimg/node:18.7.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn build
      - run:
          name: Run tests
          command: yarn run test:unit
