version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test: 
    docker:
      - image: cimg/node:18.7.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: "yarn"
      - run:
          name: Run tests
          command: yarn run test:unit
